package com.facebank.clients;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ValidClientDataList2 implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.util.List<com.facebank.clients.ValidClientData> validClientData;

	public ValidClientDataList2() {
	}

	public java.util.List<com.facebank.clients.ValidClientData> getValidClientData() {
		return this.validClientData;
	}

	public void setValidClientData(
			java.util.List<com.facebank.clients.ValidClientData> validClientData) {
		this.validClientData = validClientData;
	}

	public ValidClientDataList2(
			java.util.List<com.facebank.clients.ValidClientData> validClientData) {
		this.validClientData = validClientData;
	}

}