package com.facebank.clients;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ValidDataList implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public ValidDataList() {
    }




}