package com.facebank.clients;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ValidData implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public ValidData() {
    }




}