package com.facebank.clients;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ValidClientData implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String variableName;

	private java.lang.Boolean valid;

	public ValidClientData() {
	}

	public java.lang.String getVariableName() {
		return this.variableName;
	}

	public void setVariableName(java.lang.String variableName) {
		this.variableName = variableName;
	}

	public java.lang.Boolean getValid() {
		return this.valid;
	}

	public void setValid(java.lang.Boolean valid) {
		this.valid = valid;
	}

	public ValidClientData(java.lang.String variableName,
			java.lang.Boolean valid) {
		this.variableName = variableName;
		this.valid = valid;
	}

}