package com.facebank.clients;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ValidClientData implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String variableName;

	private java.lang.String showNamesa;

	public ValidClientData() {
	}

	public java.lang.String getVariableName() {
		return this.variableName;
	}

	public void setVariableName(java.lang.String variableName) {
		this.variableName = variableName;
	}

	public java.lang.String getShowNamesa() {
		return this.showNamesa;
	}

	public void setShowNamesa(java.lang.String showNamesa) {
		this.showNamesa = showNamesa;
	}

	public ValidClientData(java.lang.String variableName,
			java.lang.String showNamesa) {
		this.variableName = variableName;
		this.showNamesa = showNamesa;
	}

}