package com.facebank.clients;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ValidClientDataList implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.util.List<com.facebank.clients.ValidClientData2> validClientData;

	public ValidClientDataList() {
	}

	public java.util.List<com.facebank.clients.ValidClientData2> getValidClientData() {
		return this.validClientData;
	}

	public void setValidClientData(
			java.util.List<com.facebank.clients.ValidClientData2> validClientData) {
		this.validClientData = validClientData;
	}

	public ValidClientDataList(
			java.util.List<com.facebank.clients.ValidClientData2> validClientData) {
		this.validClientData = validClientData;
	}

}